# Server settings
server:
  port: 8084
 # address: localhost
#  context-path: /carnet
#  error:
#    path: /erro
# DATASOURCE
jdbc:
    dataSourceClassName: com.mysql.jdbc.jdbc2.optional.MysqlDataSource
    url: jdbc:mysql://localhost:3306/carnet?useUnicode=true&amp;charaterEncoding=utf-8
    databaseName: carnet
    serverName: localhost
    username: root
    password: root
    cachePrepStmts: true
    prepStmtsSize: 250
    prepStmtsCacheSqlLimit: 2048
    userServerPrepStmts: true
# SPRING PROFILES
spring:
 #   datasource:
  #       primary.url: jdbc:mysql://123.206.59.168:3306/carnet?useUnicode=true&amp;charaterEncoding=utf-8
   #      primary.username: root
    #     primary.password: Ninico2015
     #    primary.driver-class-name: com.mysql.jdbc.Driver
#配置二号数据源
         #secondary.url: jdbc:mysql://123.206.59.168:3306/carnet?useUnicode=true&amp;charaterEncoding=utf-8
         #secondary.username: root
         #secondary.password: Ninico2015
         #secondary.driver-class-name: com.mysql.jdbc.Driver
    # HTTP ENCODING
    http:
        encoding.charset: UTF-8
        encoding.enable: true
        encoding.force: true
    cache:
        ehcache.config=classpath:ehcache/ehcache-login.xml
# LOGGING
logging:
    file: carnet.log
    path: log
    level:
       org.springframework.web: DEBUG
       com.earl.carnet: DEBUG
#设置文件上传大小限制
multipart:
    maxFileSize: 50Mb
    maxRequestSize: 50Mb

#本系统自定义属性(是否启用权限控制系统)
security:
    enable: false
