# Server settings
server:
  port: 8080
 # address: localhost
#  context-path: /carnet
#  error:
#    path: /erro
# DATASOURCE
jdbc:
    dataSourceClassName: com.mysql.jdbc.jdbc2.optional.MysqlDataSource
    url: jdbc:mysql://localhost:3306/carnet?useUnicode=true&amp;charaterEncoding=utf-8
    databaseName: carnet
    serverName: 127.0.0.1
    username: root
    password: root
    cachePrepStmts: true
    prepStmtsSize: 250
    prepStmtsCacheSqlLimit: 2048
    userServerPrepStmts: true
# SPRING PROFILES
spring:       
    # HTTP ENCODING
    http:
        encoding.charset: UTF-8
        encoding.enable: true
        encoding.force: true
# LOGGING
logging:
    file: carnet.log
    path: log
    level:
       org.springframework.web: DEBUG
       com.earl.carnet: DEBUG
#设置文件上传大小限制
multipart:
    maxFileSize: 50Mb
    maxRequestSize: 50Mb
